/*
 * Stray Photons - Copyright (C) 2026 Jacob Wirth
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

#include "../lib/types_common.glsl"
#include "../lib/voxel_shared.glsl"
#include "lib/scene.glsl"

layout(std430, binding = 0) buffer IndexLookupBuffer {
    uint seed;
    uint vertexCount;
    uint indexLookup[];
};

layout(std430, binding = 1) buffer IndexBuffer {
    uint indexCount;
    uint indices[];
};

#include "lib/marching_cubes.glsl"

layout(constant_id = 0) const uint GRID_SIZE_X = 32;
layout(constant_id = 1) const uint GRID_SIZE_Y = 32;
layout(constant_id = 2) const uint GRID_SIZE_Z = 32;

const ivec3 voxelGridSize = ivec3(GRID_SIZE_X, GRID_SIZE_Y, GRID_SIZE_Z);

void main() {
    ivec3 position = ivec3(gl_GlobalInvocationID);
    if (any(greaterThanEqual(position, voxelGridSize - 1))) return;

    float[8] cornerData = float[](sampleGrid(voxelGridSize, position + vertexOffset[0]),
        sampleGrid(voxelGridSize, position + vertexOffset[1]),
        sampleGrid(voxelGridSize, position + vertexOffset[2]),
        sampleGrid(voxelGridSize, position + vertexOffset[3]),
        sampleGrid(voxelGridSize, position + vertexOffset[4]),
        sampleGrid(voxelGridSize, position + vertexOffset[5]),
        sampleGrid(voxelGridSize, position + vertexOffset[6]),
        sampleGrid(voxelGridSize, position + vertexOffset[7]));

    uint caseNum = uint(cornerData[0] > 0) | uint(cornerData[2] > 0) << 1 | uint(cornerData[7] > 0) << 2 |
                   uint(cornerData[1] > 0) << 3 | uint(cornerData[3] > 0) << 4 | uint(cornerData[5] > 0) << 5 |
                   uint(cornerData[4] > 0) << 6 | uint(cornerData[6] > 0) << 7;
    if (caseNum == 0 || caseNum == 255) return;

    ivec3 cubeGridSize = max(ivec3(1), voxelGridSize - 1);
    uint posIndex = FlattenIndex(position, cubeGridSize);

    int count = caseTriangleCount[caseNum];
    for (int triangle = 0; triangle < count; triangle++) {
        ivec3 edgeNums = caseTriangles[caseNum][triangle];

        uint triangleOffset = atomicAdd(indexCount, 3);
        for (int vertex = 0; vertex < 3; vertex++) {
            uint edge = edgeNums[vertex];
            ivec4 edgeInfo = edgeLookup[edge];
            uint edgeIndex = FlattenIndex(position + edgeInfo.xyz, cubeGridSize) * 3 + edgeInfo.w;

            indices[triangleOffset + vertex] = indexLookup[edgeIndex];
        }
    }
}
