/*
 * Stray Photons - Copyright (C) 2026 Jacob Wirth
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

#include "../lib/types_common.glsl"
#include "../lib/voxel_shared.glsl"
#include "lib/scene.glsl"

layout(binding = 0) uniform VoxelStateUniform {
    VoxelState voxelInfo;
};

layout(binding = 1) uniform sampler3D voxelRadiance;

layout(std430, binding = 2) buffer IndexLookupBuffer {
    uint time;
    uint vertexCount;
    uint indexLookup[];
};

layout(std430, binding = 3) buffer IndexBuffer {
    VkDrawIndexedIndirectCommand drawCmd;
    uint indices[];
};

#include "lib/marching_cubes.glsl"

layout(constant_id = 0) const int CUBE_LAYER = 0;

void main() {
    ivec3 position = ivec3(gl_GlobalInvocationID);
    if (any(greaterThanEqual(position, (voxelInfo.gridSize >> CUBE_LAYER) - 2))) return;

    float[8] cornerData = float[](sampleGrid(voxelRadiance, position + vertexOffset[0]),
        sampleGrid(voxelRadiance, position + vertexOffset[1]),
        sampleGrid(voxelRadiance, position + vertexOffset[2]),
        sampleGrid(voxelRadiance, position + vertexOffset[3]),
        sampleGrid(voxelRadiance, position + vertexOffset[4]),
        sampleGrid(voxelRadiance, position + vertexOffset[5]),
        sampleGrid(voxelRadiance, position + vertexOffset[6]),
        sampleGrid(voxelRadiance, position + vertexOffset[7]));

    // uint caseNum = uint(cornerData[0] > 0) | uint(cornerData[1] > 0) << 1 | uint(cornerData[2] > 0) << 2 |
    //                uint(cornerData[3] > 0) << 3 | uint(cornerData[4] > 0) << 4 | uint(cornerData[5] > 0) << 5 |
    //                uint(cornerData[6] > 0) << 6 | uint(cornerData[7] > 0) << 7;
    uint caseNum = uint(cornerData[0] > 0) | uint(cornerData[2] > 0) << 1 | uint(cornerData[7] > 0) << 2 |
                   uint(cornerData[1] > 0) << 3 | uint(cornerData[3] > 0) << 4 | uint(cornerData[5] > 0) << 5 |
                   uint(cornerData[4] > 0) << 6 | uint(cornerData[6] > 0) << 7;
    if (caseNum == 0 || caseNum == 255) return;

    ivec3 cubeGridSize = max(ivec3(1), (voxelInfo.gridSize >> CUBE_LAYER) - 1);
    uint posIndex = FlattenIndex(position, cubeGridSize);

    int count = caseTriangleCount[caseNum];
    for (int triangle = 0; triangle < count; triangle++) {
        ivec3 edgeNums = caseTriangles[caseNum][triangle];

        uint triangleOffset = atomicAdd(drawCmd.indexCount, 3);
        for (int vertex = 0; vertex < 3; vertex++) {
            uint edge = edgeNums[vertex];
            ivec4 edgeInfo = edgeLookup[edge];
            uint edgeIndex = FlattenIndex(position + edgeInfo.xyz, cubeGridSize) * 3 + edgeInfo.w;

            indices[triangleOffset + vertex] = indexLookup[edgeIndex];
        }
    }
    // drawCmd.indexCount = vertexCount;
}
