[package]
name = "sp-sys"
version = "0.1.0"
authors = ["xthexder", "nauscar"]
edition = "2021"
license-file = "../../LICENSE-MPL-2.0"

[features]
default = []
debug = []

[build-dependencies]
cmake = "0.1"
