
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)

if (WIN32)
	set(GLFW_USE_HYBRID_HPG ON)
endif()

set(GLFW_USE_EGLHEADLESS ON)

add_subdirectory(glfw)