option(NO_OPENCL "NO_OPENCL" ON)
option(NO_OPENMP "NO_OPENMP" ON)
set(CMAKE_COMMON_INC "../cmake_common.cmake")
set(BUILD_SHARED_LIBS off)
add_compile_options(-Wno-error=stringop-overflow=)
add_subdirectory(v-hacd/VHACD_Lib)
